version: '3.7'

services: 
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laravelapp'
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    container_name: app
  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: example
    container_name: db

  pgadmin:
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: postgres@mail.com
        PGADMIN_DEFAULT_PASSWORD: example
    ports:
      - "5050:80"
    depends_on:
      - db
    container_name: pgadmin
    